import { Providers } from '@/components/Providers'
import '@ant-design/v5-patch-for-react-19';
import '@/styles/globals.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Tuan Pham',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className="mdl-js" lang="en">
      <body>
        <Providers>{children}</Providers>

      </body>
    </html>
  )
}
